---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: app-staging
    image: ubuntu:14.04
    hash_name: ubuntu-14.04
    groups:
      - securedrop_application_server
      - staging
  - name: mon-staging
    image: ubuntu:14.04
    hash_name: ubuntu-14.04
    groups:
      - securedrop_monitor_server
      - staging
provisioner:
  name: ansible
  inventory:
    links:
      # Path is relative to .molecule folder
      group_vars: ../../../install_files/ansible-base/group_vars
  env:
    ANSIBLE_ROLES_PATH: ../../install_files/ansible-base/roles
    ANSIBLE_ACTION_PLUGINS: ../../install_files/ansible-base/action_plugins
  lint:
    name: ansible-lint
scenario:
  name: staging
  test_sequence:
    - destroy
    - create
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  options:
    # provided by pytest-xdist
    n: auto
  lint:
    name: flake8
